#!/usr/bin/env python3
import argparse
import collections
import os
import stat

class InstException(Exception):
    pass


def parse_args():
    pars = argparse.ArgumentParser(description="skel installer")
    mode = pars.add_mutually_exclusive_group()
    mode.add_argument("--symlink", action="store_true",
                      help="Instead of copying the files, symlink them")
    mode.add_argument("--hardlink", action="store_true",
                      help="Instead of copying the files, hardlink them")
    pars.add_argument("--to-etc-skel", action="store_true",
                      help="Instead of ~, install to /etc/skel")
    pars.add_argument("skeldir", nargs="+",
                      help="Source directory for installation")

    return pars.parse_args()


def main():
    args = parse_args()
    if args.to_etc_skel:
        tgtdir = "/etc/skel"
    else:
        tgtdir = os.environ["HOME"]

    # lists of file actions to perform
    mkdirlist = []
    installlist = []
    dupeinstalls = {}
    warnings = []

    # scan skeldir, check for actions to perform (fill mkdirlist, installlist)
    for skeldir in args.skeldir:
        if not os.path.isdir(skeldir):
            raise InstException("not a directory: " + skeldir)

        searchqueue = collections.deque([(skeldir, tgtdir)])

        while len(searchqueue) > 0:
            srcdirname, tgtdirname = searchqueue.pop()

            for f in sorted(os.listdir(srcdirname)):
                srcfile = srcdirname + "/" + f
                tgtfile = tgtdirname + "/" + f

                if os.path.islink(srcfile):
                    raise InstException("symlink: " + srcfile)

                if os.path.isdir(srcfile):
                    # it's a dir, so we need to create that if not exists
                    if os.path.exists(tgtfile):
                        if os.path.isdir(tgtfile):
                            # dir already exists, everything's fine
                            pass
                        else:
                            # there is a file with that name
                            raise InstException("Existing file " + tgtfile +
                                                " blocks directory creation")
                    else:
                        # we need to create the dir
                        if tgtfile not in mkdirlist:
                            mkdirlist.append(tgtfile)

                    # recursively search that dir, too
                    searchqueue.appendleft((srcfile, tgtfile))

                else:
                    # it's a file, so we need to copy it
                    if os.path.exists(tgtfile):
                        if os.path.isdir(tgtfile):
                            raise InstException("Existing dir " + tgtfile +
                                                " prevents file installation")

                        # check whether the file differs
                        tgtdata = open(tgtfile, 'rb').read()
                        srcdata = open(srcfile, 'rb').read()
                        if tgtdata == srcdata:
                            continue

                        exists = True
                    else:
                        exists = False

                    if tgtfile in dupeinstalls:
                        warnings.append(tgtfile + " from \x1b[1m" +
                              dupeinstalls[tgtfile] + "\x1b[m obsolted by " +
                              "\x1b[1m" + skeldir + "\x1b[m")

                        installlist = [entry for entry in installlist if
                                       entry[1] != tgtfile]

                    dupeinstalls[tgtfile] = skeldir

                    installlist.append((srcfile, tgtfile, exists, skeldir))


    if not installlist and not mkdirlist:
        raise InstException("Nothing to be installed")

    # ask for user confirmation
    if mkdirlist:
        print("The following directories will be created:\n\n" +
              "\n".join(mkdirlist) + "\n")

    if installlist:
        print("The following files will be installed:\n")

        maxtgtfilelen = len(max(installlist, key=lambda x: len(x[1]))[1])
        maxskeldirlen = len(max(installlist, key=lambda x: len(x[3]))[3])

        for _, tgtfile, exists, skeldir in installlist:
            if exists:
                warning = "\x1b[31;1m[Overwriting existing file!]\x1b[m"
            else:
                warning = ""

            print(tgtfile.ljust(maxtgtfilelen) + " from \x1b[1m" +
                  skeldir.ljust(maxskeldirlen) + "\x1b[m " + warning)

        print("")

    if warnings:
        print("\x1b[1;33m[Warnings]\x1b[m\n")
        for warning in warnings:
            print(warning)

        print("")

    i = input("Continue [Y/n]? ")
    if i not in {"Y", "y", ""}:
        raise InstException("Aborted by user")

    # do installation
    # create directories
    for tgtfile in mkdirlist:
        print("mkdir " + tgtfile)
        os.mkdir(tgtfile)

    # install files
    for srcfile, tgtfile, exists, _ in installlist:
        if exists:
            print("rm " + tgtfile)
            os.unlink(tgtfile)

        if args.symlink:
            print("ln -s " + srcfile + " " + tgtfile)
            os.symlink(srcfile, tgtfile)
        elif args.hardlink:
            print("ln " + srcfile + " " + tgtfile)
            os.link(srcfile, tgtfile)
        else:
            print("cp " + srcfile + " " + tgtfile)
            data = open(srcfile, "rb").read()
            open(tgtfile, "wb").write(data)

            if os.stat(srcfile).st_mode & stat.S_IEXEC:
                #set x flag
                os.stat(tgtfile, os.stat(tgtfile).st_mode | stat.S_IEXEC)

if __name__ == "__main__":
    try:
        main()
    except InstException as e:
        print(e)
    except KeyboardInterrupt:
        print("\nInterrupted by user")
